hello/urls.py
from django.urls import path
from hello import views

urlpatterns = [
    path("buildings/create/", views.BuildingCreate.as_view(), name="building-create"),
    path("buildings/", views.BuildingList.as_view(), name="building-list"),
    path("buildings/<pk>/", views.BuildingDetails.as_view(), name="building-details"),
    path("buildings/<pk>/edit", views.BuildingUpdate.as_view(), name="building-update"),
    path("buildings/<pk>/delete", views.BuildingDelete.as_view(), name="building-delete"),

    path("building_series/create/", views.BuildingSeriesCreate.as_view(), name="series-create"),
    path("building_series/", views.BuildingSeriesList.as_view(), name="series-list"),
    path("building_series/<pk>/", views.BuildingSeriesDetails.as_view(), name="series-details"),
    path("building_series/<pk>/edit", views.BuildingSeriesUpdate.as_view(), name="series-update"),
    path("building_series/<pk>/delete", views.BuildingSeriesDelete.as_view(), name="series-delete"),
]

hello_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls"))
]

hello/models.py
import uuid
from django.db import models

# Create your models here.
class BuildingSeries(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    name = models.CharField(max_length=128)

    def __str__(self) -> str:
        return f"Series {self.name} ({self.id})"


class Building(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    address = models.CharField(max_length=128)
    floor_count = models.IntegerField()
    build_date = models.DateField()
    series = models.ForeignKey(BuildingSeries, on_delete=models.SET_NULL, null=True, blank=True)

hello/forms.py
from django import forms
from django.forms import models
from hello.models import Building

class BuildingForm(forms.ModelForm):
    class Meta:
        model = Building
        fields = ["address", "floor_count", "build_date"]

hello/views.py
from django.db import models
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from hello.models import Building, BuildingSeries

class BuildingSeriesCreate(CreateView):
    model = BuildingSeries

    fields = ["name"]

    success_url = reverse_lazy("series-list")

class BuildingSeriesList(ListView):
    model = BuildingSeries

class BuildingSeriesDetails(DetailView):
    model = BuildingSeries

class BuildingSeriesUpdate(UpdateView):
    model = BuildingSeries

    fields = ["name"]

class BuildingSeriesDelete(DeleteView):
    model = BuildingSeries

    success_url = reverse_lazy("series-list")

class BuildingCreate(CreateView):
    model = Building

    fields = ["address", "floor_count", "build_date", "series"]

    success_url = reverse_lazy("building-list")

class BuildingList(ListView):
    model = Building

class BuildingDetails(DetailView):
    model = Building

class BuildingUpdate(UpdateView):
    model = Building

    fields = ["address", "floor_count", "build_date", "series"]

class BuildingDelete(DeleteView):
    model = Building

    success_url = reverse_lazy("building-list")

templates/base.html
{% extends 'bootstrap5/bootstrap5.html' %}

{% load bootstrap5 %}

<h2>Hello App</h2>

{% block bootstrap5_content %}
<div style="padding: 10%;">
{% block content %}
{% endblock content %}
</div>
{% endblock bootstrap5_content %}

templates/hello/building_detail.html
{% extends 'base.html' %}

{% block content %}
<h3> {{ object.address }} </h3>

<p>
    {{ object.floor_count }} floors <br>
    Series: <a href="{% url 'series-details' pk=object.series.id %}">{{ object.series.name }}</a> <br>
    Built in {{ object.build_date }}
<p>

<a href="/hello/buildings/"> Back to list </a>
{% endblock content %}

templates/hello/building_form.html
{% extends 'base.html' %}

{% load bootstrap5 %}

{% block content %}
<form method="POST" class="form">

     {% csrf_token %}
     {% bootstrap_form form %}

    {% buttons %}
    <input type="submit" value="Create" class="btn btn-primary">
    {% endbuttons %}

</form>
{% endblock content %}

templates/hello/building_list.html
{% extends 'base.html' %}

{% block content %}
<h3>Building list</h3>

<a href="{% url 'building-create' %}">Create new</a>

<ul>
    {% for object in object_list %}
    <li>
        <b>{{ object.address }}</b>
        <br>
        Build date: {{ object.build_date }}, {{ object.floor_count }} floors
        {% if object.series %}
        , series <a href="{% url 'series-details' pk=object.series.id %}">{{ object.series.name }}</a>
        {% endif %}
        <p>
            <a href="{% url 'building-update' pk=object.id %}">Edit</a> |
            <a href="{% url 'building-details' pk=object.id %}">Details</a> |
            <a href="{% url 'building-delete' pk=object.id %}">Delete</a>
        </p>
    </li>
    <hr />
    {% endfor %}
</ul>
{% endblock content %}

templates/hello/buildingseries_detail.html
{% extends 'base.html' %}

{% block content %}
<h3> {{ object.name }} </h3>

<p> Buildings in database: {{ object.building_set.all.count }} </p>

<a href="{% url 'series-list' %}"> Back to list </a>
{% endblock content %}

templates/hello/buildingseries_form.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">

     {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="Create">

</form>
{% endblock content %}

templates/hello/buildingseries_list.html
{% extends 'base.html' %}

{% block content %}
<h3>Series list</h3>

<ul>
    {% for object in object_list %}
    <li>
        <b>{{ object.name }}</b>
        <p>
            <a href="{% url 'series-update' pk=object.id %}">Edit</a> |
            <a href="{% url 'series-details' pk=object.id %}">Details</a> |
            <a href="{% url 'series-delete' pk=object.id %}">Delete</a>
        </p>
    </li>
    <hr />
    {% endfor %}
</ul>
{% endblock content %}